"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireRole } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

const text = z.string().trim().min(1).max(160);
const money = z.coerce.number().int().min(0).max(1000000000);
const uuid = z.string().uuid();
const optional = z.string().trim().max(500).optional().or(z.literal(""));
const dateOnly = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().or(z.literal(""));
const studentAccount = z.object({ name: text, email: z.string().email(), phone: optional, studentId: z.string().trim().regex(/^[A-Za-z0-9-]{3,40}$/), password: z.string().min(10).max(128), classId: z.string().uuid().optional().or(z.literal("")), batchId: z.string().uuid().optional().or(z.literal("")), rollNumber: optional });
const teacherAccount = z.object({ name: text, email: z.string().email(), phone: optional, teacherId: z.string().trim().regex(/^[A-Za-z0-9-]{3,40}$/), password: z.string().min(10).max(128), qualification: optional, experience: z.coerce.number().int().min(0).max(80) });

function value(form: FormData, key: string) { return String(form.get(key) ?? ""); }
async function adminDb() { await requireRole("ADMIN"); return createClient(); }
function refresh(path: string) { revalidatePath(path); revalidatePath("/admin"); }

export async function createStudent(form: FormData) {
  const data = studentAccount.parse({ name:value(form,"name"), email:value(form,"email"), phone:value(form,"phone"), studentId:value(form,"studentId"), password:value(form,"password"), classId:value(form,"classId"), batchId:value(form,"batchId"), rollNumber:value(form,"rollNumber") });
  await requireRole("ADMIN"); const supabase = createAdminClient();
  const { data: auth, error } = await supabase.auth.admin.createUser({ email:data.email.toLowerCase(), password:data.password, email_confirm:true });
  if (error || !auth.user) throw new Error(error?.message ?? "Could not create the Auth user.");
  const { data: profile, error: profileError } = await supabase.from("profiles").insert({ user_id:auth.user.id, role:"STUDENT", name:data.name, email:data.email.toLowerCase(), phone:data.phone || null }).select("id").single();
  if (profileError || !profile) { await supabase.auth.admin.deleteUser(auth.user.id); throw new Error(profileError?.message ?? "Could not create the student profile."); }
  const { error: studentError } = await supabase.from("students").insert({ profile_id:profile.id, student_id:data.studentId, class_id:data.classId || null, batch_id:data.batchId || null, roll_number:data.rollNumber || null });
  if (studentError) { await supabase.from("profiles").delete().eq("id", profile.id); await supabase.auth.admin.deleteUser(auth.user.id); throw new Error(studentError.message); }
  refresh("/admin/students");
}
export async function createTeacher(form: FormData) {
  const data = teacherAccount.parse({ name:value(form,"name"), email:value(form,"email"), phone:value(form,"phone"), teacherId:value(form,"teacherId"), password:value(form,"password"), qualification:value(form,"qualification"), experience:value(form,"experience") });
  await requireRole("ADMIN"); const supabase = createAdminClient();
  const { data: auth, error } = await supabase.auth.admin.createUser({ email:data.email.toLowerCase(), password:data.password, email_confirm:true });
  if (error || !auth.user) throw new Error(error?.message ?? "Could not create the Auth user.");
  const { data: profile, error: profileError } = await supabase.from("profiles").insert({ user_id:auth.user.id, role:"TEACHER", name:data.name, email:data.email.toLowerCase(), phone:data.phone || null }).select("id").single();
  if (profileError || !profile) { await supabase.auth.admin.deleteUser(auth.user.id); throw new Error(profileError?.message ?? "Could not create the teacher profile."); }
  const { error: teacherError } = await supabase.from("teachers").insert({ profile_id:profile.id, teacher_id:data.teacherId, qualification:data.qualification || null, experience:data.experience });
  if (teacherError) { await supabase.from("profiles").delete().eq("id", profile.id); await supabase.auth.admin.deleteUser(auth.user.id); throw new Error(teacherError.message); }
  refresh("/admin/teachers");
}
export async function setProfileActive(form: FormData) { const supabase=await adminDb(); const id=uuid.parse(value(form,"profileId")); const active=value(form,"active")==="true"; const {error}=await supabase.from("profiles").update({is_active:active}).eq("id",id); if(error) throw new Error(error.message); refresh(value(form,"path")); }
export async function createClass(form: FormData) { const supabase=await adminDb(); const name=z.enum(["7","8","9","10","11","12"]).parse(value(form,"name")); const {error}=await supabase.from("classes").insert({name}); if(error) throw new Error(error.message); refresh("/admin/classes"); }
export async function createSubject(form: FormData) { const supabase=await adminDb(); const name=text.parse(value(form,"name")); const {error}=await supabase.from("subjects").insert({name}); if(error) throw new Error(error.message); refresh("/admin/subjects"); }
export async function createBatch(form: FormData) { const supabase=await adminDb(); const data={name:text.parse(value(form,"name")),class_id:uuid.parse(value(form,"classId")),timing:optional.parse(value(form,"timing"))||null,days:optional.parse(value(form,"days"))||null,room:optional.parse(value(form,"room"))||null}; const {error}=await supabase.from("batches").insert(data); if(error) throw new Error(error.message); refresh("/admin/batches"); }
export async function assignSubjectToClass(form: FormData) { const supabase=await adminDb(); const classId=uuid.parse(value(form,"classId")); const subjectId=uuid.parse(value(form,"subjectId")); const {data:existing,error:existingError}=await supabase.from("class_subjects").select("class_id").eq("class_id",classId).eq("subject_id",subjectId).maybeSingle(); if(existingError) throw new Error(existingError.message); if(existing) throw new Error("This subject is already assigned to the class."); const {error}=await supabase.from("class_subjects").insert({class_id:classId,subject_id:subjectId}); if(error) throw new Error(error.code==="23505"?"This subject is already assigned to the class.":error.message); refresh("/admin/class-subjects"); refresh("/admin/classes"); }
export async function removeSubjectFromClass(form: FormData) { const supabase=await adminDb(); const classId=uuid.parse(value(form,"classId")); const subjectId=uuid.parse(value(form,"subjectId")); const {error}=await supabase.from("class_subjects").delete().eq("class_id",classId).eq("subject_id",subjectId); if(error) throw new Error(error.message); refresh("/admin/class-subjects"); refresh("/admin/classes"); }
export async function createFeeAssignment(form: FormData) { const supabase=await adminDb(); const data={student_id:uuid.parse(value(form,"studentId")),fee_structure_id:value(form,"structureId")?uuid.parse(value(form,"structureId")):null,amount:money.parse(value(form,"amount")),due_date:value(form,"dueDate")||null,notes:optional.parse(value(form,"notes"))||null}; const {error}=await supabase.from("student_fee_assignments").insert(data); if(error) throw new Error(error.message); refresh("/admin/fees"); }
export async function recordManualPayment(form: FormData) { const supabase=await adminDb(); const assignmentId=uuid.parse(value(form,"assignmentId")); const amount=money.parse(value(form,"amount")); if(amount<=0) throw new Error("Payment must be greater than zero."); const {data: assignment,error:assignmentError}=await supabase.from("student_fee_assignments").select("id,student_id,amount,due_date").eq("id",assignmentId).single(); if(assignmentError||!assignment) throw new Error("Fee assignment not found."); const {data: payments,error:paymentsError}=await supabase.from("fee_payments").select("amount").eq("fee_assignment_id",assignmentId).eq("payment_status","SUCCESS"); if(paymentsError) throw new Error(paymentsError.message); const paid=(payments??[]).reduce((sum,p)=>sum+Number(p.amount),0)+amount; if(paid>Number(assignment.amount)) throw new Error("Payment exceeds the remaining amount."); const receipt=`MA-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`; const {error}=await supabase.from("fee_payments").insert({student_id:assignment.student_id,fee_assignment_id:assignmentId,amount,payment_method:z.enum(["CASH","UPI","CARD","BANK_TRANSFER","ONLINE"]).parse(value(form,"method")),payment_status:"SUCCESS",paid_at:new Date().toISOString(),receipt_number:receipt,transaction_reference:optional.parse(value(form,"reference"))||null,notes:optional.parse(value(form,"notes"))||null}); if(error) throw new Error(error.message); const remaining=Number(assignment.amount)-paid; const status=remaining===0?"PAID":(assignment.due_date&&new Date(String(assignment.due_date))<new Date()?"OVERDUE":"PARTIAL"); const {error:updateError}=await supabase.from("student_fee_assignments").update({status}).eq("id",assignmentId); if(updateError) throw new Error(updateError.message); refresh("/admin/fees"); revalidatePath("/student/fees"); }
export async function createNotice(form: FormData) { const supabase=await adminDb(); const published=value(form,"published")==="on"; const publishDate=dateOnly.parse(value(form,"publishDate")); const publishedAt=published?(publishDate?new Date(`${publishDate}T00:00:00.000Z`).toISOString():new Date().toISOString()):null; const data={title:text.parse(value(form,"title")),description:z.string().trim().min(1).max(3000).parse(value(form,"description")),audience:z.enum(["ALL","STUDENTS","TEACHERS","PARENTS"]).parse(value(form,"audience")),is_published:published,published_at:publishedAt}; const {error}=await supabase.from("notices").insert(data); if(error) throw new Error(error.message); refresh("/admin/notices"); }
export async function setNoticePublished(form: FormData) { const supabase=await adminDb(); const id=uuid.parse(value(form,"noticeId")); const published=value(form,"published")==="true"; const {error}=await supabase.from("notices").update({is_published:published,published_at:published?new Date().toISOString():null}).eq("id",id); if(error) throw new Error(error.message); refresh("/admin/notices"); }
export async function saveSettings(form: FormData) { const supabase=await adminDb(); const data={id:true,academy_name:text.parse(value(form,"academyName")),address:optional.parse(value(form,"address"))||null,phone:optional.parse(value(form,"phone"))||null,email:value(form,"email")?z.string().email().parse(value(form,"email")):null,website:optional.parse(value(form,"website"))||null,logo_url:optional.parse(value(form,"logoUrl"))||null,updated_at:new Date().toISOString()}; const {error}=await supabase.from("academy_settings").upsert(data); if(error) throw new Error(error.message); refresh("/admin/settings"); }
